name: cr_logger_example
description: Demonstrates how to use the cr_logger plugin.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  chopper: ^7.0.6
  cr_logger:
    path: ../
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dropzone: ^3.0.5
  logger: ^1.1.0
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue-Medium.ttf
        - asset: fonts/Epilogue-Regular.ttf
