name: cr_logger
description: Powerful logging plugin. Supports android, ios and web platforms.

version: 2.3.0
homepage: https://github.com/Cleveroad/cr_logger

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  app_settings: ^5.1.1
  chopper: null
  cr_json_widget: ^1.1.0
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.0.0
  infinite_scroll_pagination: ^3.2.0
  inspector: ^1.1.0
  js: ^0.6.0
  logger: ^1.1.0
  package_info_plus: ^4.1.0
  path: ^1.8.2
  path_provider: ^2.0.0
  platform: ^3.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.0.0
  split_view: ^3.2.0
  sqflite: ^2.2.0+3
  synchronized: ^3.0.0
  uuid: ^3.0.0
  worker_manager: ^5.0.0

dev_dependencies:
  build_runner: ^2.2.0
  # MIT
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue-Medium.ttf
        - asset: fonts/Epilogue-Regular.ttf

  plugin:
    platforms:
      android:
        package: com.cleveroad.cr_logger.cr_logger
        pluginClass: CrLoggerPlugin
      ios:
        pluginClass: CrLoggerPlugin
      web:
        pluginClass: CrLoggerWeb
        fileName: cr_logger_web.dart
